In [ ]:
best_episodes = (lambda: _deepnote_execute_sql('WITH best_note AS(\n    SELECT MAX(rating) AS max_note\n    FROM \'one piece episodes ranks new.csv\'\n)\nSELECT a.ep_num AS episode_number,\n    a.episode_english_title AS episode_name\nFROM \'one piece episodes ranks new.csv\' AS a,\n    best_note AS b\nWHERE a.rating = b.max_note\nORDER BY episode_number', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled') if '_deepnote_execute_sql' in globals() else _dntk.execute_sql('WITH best_note AS(\n    SELECT MAX(rating) AS max_note\n    FROM \'one piece episodes ranks new.csv\'\n)\nSELECT a.ep_num AS episode_number,\n    a.episode_english_title AS episode_name\nFROM \'one piece episodes ranks new.csv\' AS a,\n    best_note AS b\nWHERE a.rating = b.max_note\nORDER BY episode_number', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled'))()
best_episodes

   episode_number                                       episode_name
0             405  Eliminated Friends! The Final Day of the Straw...
1             484  The Navy Headquarters Falls! Whitebeard's Unsp...
2             485  Ending the Matter! Whitebeard vs. the Blackbea...
3            1100      Powers on a Different Level! Luffy vs. Lucci!

In [ ]:
best_arcs = (lambda: _deepnote_execute_sql('WITH arc_note AS(\n    SELECT arc,\n        ROUND(AVG(rating),2) AS note\n    FROM \'one piece episodes ranks new.csv\'\n    --Exclude not cannon episodes\n    WHERE type NOT IN (\'Filler\',\'Anime Canon\')\n    GROUP BY ARC\n)\nSELECT arc,\n        note\nFROM arc_note\nORDER BY note desc\nLIMIT 3', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled') if '_deepnote_execute_sql' in globals() else _dntk.execute_sql('WITH arc_note AS(\n    SELECT arc,\n        ROUND(AVG(rating),2) AS note\n    FROM \'one piece episodes ranks new.csv\'\n    --Exclude not cannon episodes\n    WHERE type NOT IN (\'Filler\',\'Anime Canon\')\n    GROUP BY ARC\n)\nSELECT arc,\n        note\nFROM arc_note\nORDER BY note desc\nLIMIT 3', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled'))()
best_arcs

                       arc  note
0           Marineford Arc  9.33
1              Egghead Arc  8.90
2  Wano Country Arc Part 1  8.68

In [ ]:
worst_arcs = (lambda: _deepnote_execute_sql('WITH arc_note AS(\n    SELECT arc,\n        ROUND(AVG(rating),2) AS note\n    FROM \'one piece episodes ranks new.csv\'\n    --Exclude unfinished arcs\n    WHERE arc <> \'Egghead Arc\'\n    --Exclude not cannon episodes\n    AND type NOT IN (\'Filler\',\'Anime Canon\')\n    GROUP BY ARC\n)\nSELECT arc,\n        note\nFROM arc_note\nORDER BY note asc\nLIMIT 3', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled') if '_deepnote_execute_sql' in globals() else _dntk.execute_sql('WITH arc_note AS(\n    SELECT arc,\n        ROUND(AVG(rating),2) AS note\n    FROM \'one piece episodes ranks new.csv\'\n    --Exclude unfinished arcs\n    WHERE arc <> \'Egghead Arc\'\n    --Exclude not cannon episodes\n    AND type NOT IN (\'Filler\',\'Anime Canon\')\n    GROUP BY ARC\n)\nSELECT arc,\n        note\nFROM arc_note\nORDER BY note asc\nLIMIT 3', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled'))()
worst_arcs

                     arc  note
0   Buggy Side Story Arc  6.25
1      Foxy's Return Arc  6.50
2  Koby and Helmeppo Arc  6.70

In [ ]:
arcs_duration = (lambda: _deepnote_execute_sql('WITH arc_time AS(\n    SELECT arc,\n        count(ep_num) AS number_episodes,\n        SUM(\n            --Transform strings into integers\n            CAST(\n                LEFT(\n                        --Treatment: when duration wasnt given, consider as 25 minutes\n                        CASE WHEN ep_duration = \'NA\' THEN \'25m\' ELSE ep_duration END\n                    ,2)\n                 AS INT)\n            ) AS total_duration\n    FROM \'one piece episodes ranks new.csv\'\n    --Exclude not cannon episodes\n    WHERE type NOT IN (\'Filler\',\'Anime Canon\')\n    GROUP BY ARC\n)\nSELECT  arc,\n        number_episodes as canon_episodes,\n        total_duration as time_in_minutes,\n        round(total_duration/60,2) as time_in_hours\nFROM arc_time\nORDER BY total_duration desc', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled') if '_deepnote_execute_sql' in globals() else _dntk.execute_sql('WITH arc_time AS(\n    SELECT arc,\n        count(ep_num) AS number_episodes,\n        SUM(\n            --Transform strings into integers\n            CAST(\n                LEFT(\n                        --Treatment: when duration wasnt given, consider as 25 minutes\n                        CASE WHEN ep_duration = \'NA\' THEN \'25m\' ELSE ep_duration END\n                    ,2)\n                 AS INT)\n            ) AS total_duration\n    FROM \'one piece episodes ranks new.csv\'\n    --Exclude not cannon episodes\n    WHERE type NOT IN (\'Filler\',\'Anime Canon\')\n    GROUP BY ARC\n)\nSELECT  arc,\n        number_episodes as canon_episodes,\n        total_duration as time_in_minutes,\n        round(total_duration/60,2) as time_in_hours\nFROM arc_time\nORDER BY total_duration desc', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled'))()
arcs_duration

                        arc  canon_episodes  time_in_minutes  time_in_hours
0   Wano Country Arc Part 2             131           3231.0          53.85
1             Dressrosa Arc             117           2919.0          48.65
2     Whole Cake Island Arc              95           2369.0          39.48
3   Wano Country Arc Part 3              54           1349.0          22.48
4       Fish-Man Island Arc              51           1275.0          21.25
5           Punk Hazard Arc              46           1140.0          19.00
6         Thriller Bark Arc              45           1089.0          18.15
7               Skypiea Arc              43           1074.0          17.90
8           Enies Lobby Arc              41           1020.0          17.00
9               Water 7 Arc              37            923.0          15.38
10             Arabasta Arc              35            870.0          14.50
11           Marineford Arc              31            768.0          12.80
12                  Zou Arc              28            700.0          11.67
13    Impel Down Arc Part 2              23            575.0           9.58
14             Post-War Arc              22            550.0           9.17
15  Sabaody Archipelago Arc              21            522.0           8.70
16          Arlong Park Arc              15            372.0           6.20
17          Drum Island Arc              14            347.0           5.78
18               Levely Arc              12            300.0           5.00
19              Baratie Arc              12            293.0           4.88
20          Amazon Lily Arc              11            275.0           4.58
21     Post-Enies Lobby Arc              10            250.0           4.17
22        Syrup Village Arc              10            248.0           4.13
23  Long Ring Long Land Arc               9            225.0           3.75
24                 Jaya Arc               9            224.0           3.73
25        Little Garden Arc               8            188.0           3.13
26    Return to Sabaody Arc               6            150.0           2.50
27  Wano Country Arc Part 1               5            125.0           2.08
28          Orange Town Arc               5            123.0           2.05
29    Impel Down Arc Part 1               4            100.0           1.67
30            Loguetown Arc               4             99.0           1.65
31          Whisky Peak Arc               4             97.0           1.62
32         Romance Dawn Arc               3             73.0           1.22
33     Buggy Side Story Arc               2             50.0           0.83
34     Reverse Mountain Arc               2             50.0           0.83
35    Koby and Helmeppo Arc               2             47.0           0.78
36       Warship Island Arc               1             25.0           0.42
37        Foxy's Return Arc               1             25.0           0.42
38     Caesar Retrieval Arc               1             25.0           0.42

In [ ]:
time_to_finish = (lambda: _deepnote_execute_sql('WITH time AS(\n    SELECT type,\n        SUM(\n            --Transform strings into integers\n            CAST(\n                LEFT(\n                        --Treatment: when duration wasnt given, consider as 25 minutes\n                        CASE WHEN ep_duration = \'NA\' THEN \'25m\' ELSE ep_duration END\n                    ,2)\n                 AS INT)\n            ) AS total_duration\n    FROM \'one piece episodes ranks new.csv\'\n    --Exclude unfinished arcs\n    GROUP BY type\n)\n    SELECT \'canon\',\n        round(sum(total_duration)/60,2) as time_in_hours\n    FROM time\n    WHERE type NOT IN (\'Filler\',\'Anime Canon\')\nUNION\n    SELECT \'filler\',\n        round(sum(total_duration)/60,2) as time_in_hours\n    FROM time\n    WHERE type IN (\'Filler\',\'Anime Canon\')', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled') if '_deepnote_execute_sql' in globals() else _dntk.execute_sql('WITH time AS(\n    SELECT type,\n        SUM(\n            --Transform strings into integers\n            CAST(\n                LEFT(\n                        --Treatment: when duration wasnt given, consider as 25 minutes\n                        CASE WHEN ep_duration = \'NA\' THEN \'25m\' ELSE ep_duration END\n                    ,2)\n                 AS INT)\n            ) AS total_duration\n    FROM \'one piece episodes ranks new.csv\'\n    --Exclude unfinished arcs\n    GROUP BY type\n)\n    SELECT \'canon\',\n        round(sum(total_duration)/60,2) as time_in_hours\n    FROM time\n    WHERE type NOT IN (\'Filler\',\'Anime Canon\')\nUNION\n    SELECT \'filler\',\n        round(sum(total_duration)/60,2) as time_in_hours\n    FROM time\n    WHERE type IN (\'Filler\',\'Anime Canon\')', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled'))()
time_to_finish

  'canon'  time_in_hours
0   canon         408.92
1  filler          48.28

In [ ]:
bouties_timeline = (lambda: _deepnote_execute_sql('--Find the episodes where bounties increase\n/*WITH a AS(\n        SELECT DISTINCT "Anime episode" AS episode\n        FROM \'one piece bounties evolution.csv\' \n)\nSELECT * FROM a\n*/\n\n--Bounties timeline per episode\nSELECT *\n    FROM\n    ( SELECT Name\n            ,Bounty\n            ,"Anime episode" AS episode\n    FROM \'one piece bounties evolution.csv\' ) AS SRC\nPIVOT(\n    MAX(Bounty)\n    FOR Episode IN (43,122,128,251,320,324,381,392,430,541,746,879,980,1080,1086\n)\n) AS pt', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled') if '_deepnote_execute_sql' in globals() else _dntk.execute_sql('--Find the episodes where bounties increase\n/*WITH a AS(\n        SELECT DISTINCT "Anime episode" AS episode\n        FROM \'one piece bounties evolution.csv\' \n)\nSELECT * FROM a\n*/\n\n--Bounties timeline per episode\nSELECT *\n    FROM\n    ( SELECT Name\n            ,Bounty\n            ,"Anime episode" AS episode\n    FROM \'one piece bounties evolution.csv\' ) AS SRC\nPIVOT(\n    MAX(Bounty)\n    FOR Episode IN (43,122,128,251,320,324,381,392,430,541,746,879,980,1080,1086\n)\n) AS pt', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled'))()
bouties_timeline

,Name,43,122,128,251,320,324,381,392,430,541,746,879,980,1080,1086
0,Monkey D. Luffy,30000000.0,NaN,100000000.0,400000000.0,300000000.0,NaN,NaN,NaN,NaN,NaN,500000000.0,1.500000e+09,NaN,3.000000e+09,NaN
1,Roronoa Zoro,NaN,NaN,60000000.0,NaN,NaN,NaN,NaN,120000000.0,NaN,NaN,320000000.0,NaN,NaN,NaN,1.111000e+09
2,Nami,NaN,NaN,NaN,NaN,16000000.0,NaN,NaN,NaN,NaN,NaN,66000000.0,NaN,NaN,NaN,3.660000e+08
3,Usopp,NaN,NaN,NaN,NaN,30000000.0,NaN,NaN,NaN,NaN,NaN,200000000.0,NaN,NaN,NaN,5.000000e+08
4,Sanji,NaN,NaN,NaN,NaN,77000000.0,NaN,NaN,NaN,NaN,NaN,177000000.0,3.300000e+08,NaN,NaN,1.032000e+09
5,Tony Tony Chopper,NaN,NaN,NaN,NaN,50.0,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,1.000000e+03
6,Nico Robin,NaN,79000000.0,NaN,NaN,80000000.0,NaN,NaN,NaN,NaN,NaN,130000000.0,NaN,NaN,NaN,9.300000e+08
7,Franky,NaN,NaN,NaN,NaN,NaN,44000000.0,NaN,NaN,NaN,NaN,94000000.0,NaN,NaN,NaN,3.940000e+08
8,Brook,NaN,NaN,NaN,NaN,NaN,NaN,33000000.0,NaN,NaN,NaN,83000000.0,NaN,NaN,NaN,3.830000e+08
9,Jinbe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,250000000.0,76000000.0,NaN,NaN,438000000.0,NaN,1.100000e+09

In [ ]:
bounties_progression = (lambda: _deepnote_execute_sql('--Find the maximum number of bounties per character\n/*WITH A AS( \n    SELECT Name\n        ,COUNT(*) AS CNT\n    FROM \'one piece bounties evolution.csv\'\n    GROUP BY Name\n)\n,M AS( \n    SELECT MAX(CNT) AS M\n    FROM A \n)\nSELECT * FROM M\n*/\n\n--Number of bounties increase per character\nSELECT *\n    FROM\n    ( SELECT Name\n            ,Bounty\n            ,"Order"\n    FROM \'one piece bounties evolution.csv\') AS SRC\nPIVOT(\n    MAX(Bounty)\n    FOR "Order" IN (1 as first_bounty\n                    ,2 as second_bounty\n                    ,3 as third_bounty\n                    ,4 as fourth_bounty\n                    ,5 as fifth_bounty\n                    ,6 as sixth_bounty\n                    ,7 as seventh_bounty\n                    )\n) AS pt', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled') if '_deepnote_execute_sql' in globals() else _dntk.execute_sql('--Find the maximum number of bounties per character\n/*WITH A AS( \n    SELECT Name\n        ,COUNT(*) AS CNT\n    FROM \'one piece bounties evolution.csv\'\n    GROUP BY Name\n)\n,M AS( \n    SELECT MAX(CNT) AS M\n    FROM A \n)\nSELECT * FROM M\n*/\n\n--Number of bounties increase per character\nSELECT *\n    FROM\n    ( SELECT Name\n            ,Bounty\n            ,"Order"\n    FROM \'one piece bounties evolution.csv\') AS SRC\nPIVOT(\n    MAX(Bounty)\n    FOR "Order" IN (1 as first_bounty\n                    ,2 as second_bounty\n                    ,3 as third_bounty\n                    ,4 as fourth_bounty\n                    ,5 as fifth_bounty\n                    ,6 as sixth_bounty\n                    ,7 as seventh_bounty\n                    )\n) AS pt', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled'))()
bounties_progression

,Name,first_bounty,second_bounty,third_bounty,fourth_bounty,fifth_bounty,sixth_bounty,seventh_bounty
0,Monkey D. Luffy,30000000.0,100000000.0,300000000.0,4.000000e+08,500000000.0,1.500000e+09,3.000000e+09
1,Roronoa Zoro,60000000.0,120000000.0,320000000.0,1.111000e+09,NaN,NaN,NaN
2,Nami,16000000.0,66000000.0,366000000.0,NaN,NaN,NaN,NaN
3,Usopp,30000000.0,200000000.0,500000000.0,NaN,NaN,NaN,NaN
4,Sanji,77000000.0,177000000.0,330000000.0,1.032000e+09,NaN,NaN,NaN
5,Tony Tony Chopper,50.0,100.0,1000.0,NaN,NaN,NaN,NaN
6,Nico Robin,79000000.0,80000000.0,130000000.0,9.300000e+08,NaN,NaN,NaN
7,Franky,44000000.0,94000000.0,394000000.0,NaN,NaN,NaN,NaN
8,Brook,33000000.0,83000000.0,383000000.0,NaN,NaN,NaN,NaN
9,Jinbe,76000000.0,250000000.0,438000000.0,1.100000e+09,NaN,NaN,NaN

<img src="image-20240916-232756.png" width="" align="" />

<img src="image-20240916-232753.png" width="" align="" />

<img src="image-20240916-232657.png" width="" align="" />

<img src="image-20240916-232619.png" width="" align="" />

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=db609971-6229-4eda-9963-ddb5849b7003' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>